/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ThemeColor from './color.defs.js'

const $nsid = 'site.standard.theme.basic'

export { $nsid }

type Main = {
  $type?: 'site.standard.theme.basic'
  accent: l.TypedRef<ThemeColor.Rgb> | l.TypedObject
  background: l.TypedRef<ThemeColor.Rgb> | l.TypedObject
  foreground: l.TypedRef<ThemeColor.Rgb> | l.TypedObject
  accentForeground: l.TypedRef<ThemeColor.Rgb> | l.TypedObject
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    accent: l.typedUnion(
      [l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any)],
      false,
    ),
    background: l.typedUnion(
      [l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any)],
      false,
    ),
    foreground: l.typedUnion(
      [l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any)],
      false,
    ),
    accentForeground: l.typedUnion(
      [l.typedRef<ThemeColor.Rgb>((() => ThemeColor.rgb) as any)],
      false,
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
