import type { Metadata } from "next";
import { Atma,  Marck_Script,  Space_Grotesk } from "next/font/google";
import "./globals.css";


const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const atma = Atma({
  variable: "--font-atma",
  subsets: ["latin"],
	weight: ["300", "400", "500", "700"]
});

const marckScript = Marck_Script({
  variable: "--font-marck-script",
	weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marckScript.variable} ${spaceGrotesk.variable} ${atma.variable} antialiased custom-scroll  w-full`}
      >
        {children}
      </body>
    </html>
  );
}
