/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'site.standard.document'

export { $nsid }

type Main = {
  $type: 'site.standard.document'

  /**
   * combine with the publication url or the document site to construct a full url to the document
   */
  path?: string

  /**
   * URI to the site or publication this document belongs to (https or at-uri)
   */
  site: l.UriString
  tags?: string[]
  title: string
  content?: l.TypedObject
  updatedAt?: l.DatetimeString
  coverImage?: l.BlobRef
  bskyPostRef?: RepoStrongRef.Main
  description?: string
  publishedAt: l.DatetimeString
  textContent?: string
}

export type { Main }

const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    path: l.optional(l.string()),
    site: l.string({ format: 'uri' }),
    tags: l.optional(l.array(l.string({ maxLength: 100, maxGraphemes: 50 }))),
    title: l.string({ maxLength: 1280, maxGraphemes: 128 }),
    content: l.optional(l.typedUnion([], false)),
    updatedAt: l.optional(l.string({ format: 'datetime' })),
    coverImage: l.optional(
      l.blob({ accept: ['image/*'], maxSize: 1000000, allowLegacy: false }),
    ),
    bskyPostRef: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    description: l.optional(l.string({ maxLength: 3000, maxGraphemes: 300 })),
    publishedAt: l.string({ format: 'datetime' }),
    textContent: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
