/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ThemeBasic from './theme/basic.defs.js'

const $nsid = 'site.standard.publication'

export { $nsid }

type Main = {
  $type: 'site.standard.publication'
  url: l.UriString
  icon?: l.BlobRef
  name: string
  basicTheme?: ThemeBasic.Main
  description?: string
  preferences?: Preferences
}

export type { Main }

const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    url: l.string({ format: 'uri' }),
    icon: l.optional(
      l.blob({ accept: ['image/*'], maxSize: 1000000, allowLegacy: false }),
    ),
    name: l.string({ maxLength: 1280, maxGraphemes: 128 }),
    basicTheme: l.optional(
      l.ref<ThemeBasic.Main>((() => ThemeBasic.main) as any),
    ),
    description: l.optional(l.string({ maxLength: 3000, maxGraphemes: 300 })),
    preferences: l.optional(l.ref<Preferences>((() => preferences) as any)),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)

type Preferences = {
  $type?: 'site.standard.publication#preferences'
  showInDiscover?: boolean
}

export type { Preferences }

const preferences = l.typedObject<Preferences>(
  $nsid,
  'preferences',
  l.object({ showInDiscover: l.optional(l.boolean({ default: true })) }),
)

export { preferences }
