apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autodeploy-role
  namespace: portfolio
rules:
- apiGroups: ["", "apps", "extensions", "networking.k8s.io"]
  resources: ["pods", "deployments", "services", "replicasets", "ingresses", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
