name: Build and Deploy to K8s stagign

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read
  pull-requests: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build:
    name: Build and Push React production image to github
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SENTRY_AUTH_TOKEN=${{ env.SENTRY_AUTH_TOKEN }}

  deploy:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode Kubeconfig
        run: echo "$kubeconfig" | base64 -d > kubeconfig
        env:
          K8S_KUBECONFIG_ENCODED: ${{ secrets.kubeconfig }}

      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: kubeconfig

      - name: Get Image Tag
        id: get_image_tag
        run: |
          echo "image_tag=$(echo '${{ steps.meta.outputs.tags }}' | jq -r '.[0]')" >> "$GITHUB_OUTPUT"

      - name: Deploy to Kubernetes
        run: |
          helm upgrade -n portfolio -f ./k8s/values/staging.yaml --set image.tag="${{ steps.get_image_tag.outputs.image_tag }}"  atrin-portfolio-staging ./k8s/portfolio/


